#!/usr/bin/env python3
"""One-off replacement: translate Chinese UI/comments in source to English. Longest keys first."""
from __future__ import annotations

import re
import sys
from pathlib import Path

# (Chinese, English) — order: longest strings first to avoid partial overlaps
PAIRS: list[tuple[str, str]] = [
    ("GraphRAG长短期记忆实时更新中", "GraphRAG short/long-term memory updating live"),
    ("还有少量内容处理中，建议稍后手动刷新图谱", "Finishing a few updates — try refreshing the graph shortly"),
    ("若首次运行，强烈建议切换至‘自定义模式’减少模拟轮数，以便快速预览效果并降低报错风险 ➝", "First run? Switch to custom mode to lower round count for a quick preview and fewer errors ➝"),
    ("MiroFish 自动规划推演现实", "MiroFish plans to simulate "),
    (" 小时，每轮代表现实 ", " hours of real time; each round is "),
    (" 分钟时间流逝", " minutes of elapsed time"),
    ("若Agent规模为100：预计耗时约 ", "At ~100 agents, estimated runtime ~ "),
    ("若Agent规模为100：预计耗时 ", "At ~100 agents, estimated runtime "),
    (" 分钟", " min"),
    ("开始双世界并行模拟 ➝", "Start dual-world parallel simulation ➝"),
    ("← 返回图谱构建", "← Back to graph build"),
    ("基于叙事方向，自动生成初始激活事件与热点话题，引导模拟世界的初始状态", "From the narrative, seed initial events and hot topics to bootstrap the world"),
    ("叙事引导方向", "Narrative direction"),
    ("初始热点话题", "Initial hot topics"),
    ("初始激活序列", "Initial activation sequence"),
    ("准备完成", "Ready"),
    ("模拟环境已准备完成，可以开始运行模拟", "Environment ready — you can start the simulation"),
    ("模拟轮数设定", "Simulation rounds"),
    ("事件外显年龄", "Stated age (scenario)"),
    ("事件外显性别", "Stated gender (scenario)"),
    ("事件外显MBTI", "Stated MBTI (scenario)"),
    ("人设简介", "Persona bio"),
    ("现实种子关联话题", "Topics linked to the seed"),
    ("详细人设背景", "Detailed persona"),
    ("事件全景经历", "Full event experience"),
    ("在此事件中的完整行为轨迹", "Full behavior in this scenario"),
    ("行为模式侧写", "Behavioral profile"),
    ("经验总结与行事风格偏好", "Experience and style"),
    ("独特记忆印记", "Distinct memories"),
    ("基于现实种子形成的记忆", "Memories grounded in the seed"),
    ("社会关系网络", "Social network"),
    ("个体链接与交互图谱", "Links and interaction graph"),
    ("LLM 根据模拟需求与现实种子，智能设置世界时间流速、推荐算法、每个个体的活跃时间段、发言频率、事件触发等参数", "The LLM sets time flow, feeds, per-agent activity windows, posting rates, and triggers from your prompt and seed"),
    ("推荐算法配置", "Feed algorithm"),
    ("平台 1：广场 / 信息流", "Platform 1: plaza / feed"),
    ("平台 2：话题 / 社区", "Platform 2: topics / community"),
    ("LLM 配置推理", "LLM reasoning"),
    ("初始激活编排", "Initial activation"),
    ("生成双平台模拟配置", "Dual-platform simulation config"),
    ("结合上下文，自动调用工具从知识图谱梳理实体与关系，初始化模拟个体，并基于现实种子赋予他们独特的行为与记忆", "Uses tools over the graph to instantiate agents with behavior and memory from the seed"),
    ("已生成的 Agent 人设", "Generated agent personas"),
    ("当前Agent数", "Agents (current)"),
    ("预期Agent总数", "Agents (expected)"),
    ("现实种子当前关联话题数", "Seed topic count"),
    ("新建simulation实例，拉取模拟世界参数模版", "Creates a simulation instance and loads world templates"),
    ("模拟实例初始化", "Simulation instance"),
    ("生成 Agent 人设", "Generate agent personas"),
    ("异步任务已完成", "async task done"),
    ("本体生成", "Ontology generation"),
    ("GraphRAG构建", "GraphRAG build"),
    ("基于生成的本体，将文档自动分块后调用 Zep 构建知识图谱，提取实体和关系，并形成时序记忆与社区摘要", "Chunks documents with Zep to build the graph, entities, relations, and temporal memory"),
    ("图谱构建已完成，请进入下一步进行模拟环境搭建", "Graph build done — continue to environment setup"),
    ("进入环境搭建 ➝", "Continue to environment setup ➝"),
    ("创建模拟失败: ", "Failed to create simulation: "),
    ("创建模拟异常: ", "Simulation creation error: "),
    ("简洁通用的群体智能引擎", "A lean, general-purpose collective intelligence engine"),
    ("访问我们的Github主页", "Visit our GitHub"),
    ("v0.1-预览版", "v0.1-preview"),
    ("上传任意报告", "Upload any report"),
    ("即刻推演未来", "Simulate what comes next"),
    ('即使只有一段文字，<span class="highlight-bold">MiroFish</span> 也能基于其中的现实种子，全自动生成与之对应的至多<span class="highlight-orange">百万级Agent</span>构成的平行世界。通过上帝视角注入变量，在复杂的群体交互中寻找动态环境下的<span class="highlight-code">“局部最优解”</span>',
     'From even a short passage, <span class="highlight-bold">MiroFish</span> uses its real-world seed to automatically spin up parallel worlds with up to <span class="highlight-orange">million-scale agents</span>. Inject variables from a bird\'s-eye view and search for <span class="highlight-code">"local optima"</span> in complex group dynamics'),
    ("让未来在 Agent 群中预演，让决策在百战后胜出", "Rehearse the future in agent swarms; sharpen decisions through iteration"),
    ("系统状态", "System status"),
    ("准备就绪", "Ready"),
    ("预测引擎待命中，可上传多份非结构化数据以初始化模拟序列", "Engine idle — upload data to start a run"),
    ("低成本", "Low cost"),
    ("常规模拟平均5$/次", "~$5 per typical run"),
    ("高可用", "High scale"),
    ("最多百万级Agent模拟", "Up to million-scale agents"),
    ("工作流序列", "Workflow"),
    ("现实种子提取 & 个体与群体记忆注入 & GraphRAG构建", "Seed extraction · memory · GraphRAG"),
    ("实体关系抽取 & 人设生成 & 环境配置Agent注入仿真参数", "Entities · personas · env & sim params"),
    ("双平台并行模拟 & 自动解析预测需求 & 动态更新时序记忆", "Dual-platform sim · forecasts · temporal memory"),
    ("ReportAgent拥有丰富的工具集与模拟后环境进行深度交互", "ReportAgent with tools over the post-sim world"),
    ("与模拟世界中的任意一位进行对话 & 与ReportAgent进行对话", "Chat with anyone in the sim or ReportAgent"),
    ("01 / 现实种子", "01 / Real-world seed"),
    ("支持格式: PDF, MD, TXT", "Formats: PDF, MD, TXT"),
    ("拖拽文件上传", "Drop files to upload"),
    ("或点击浏览文件系统", "or click to browse"),
    ("输入参数", "Parameters"),
    (">_ 02 / 模拟提示词", ">_ 02 / Simulation prompt"),
    ("// 用自然语言输入模拟或预测需求（例.武大若发布撤销肖某处分的公告，会引发什么舆情走向）", "// Describe simulation or forecast needs in natural language"),
    ("引擎: MiroFish-V1.0", "Engine: MiroFish-V1.0"),
    ("启动引擎", "Start engine"),
    ("初始化中...", "Initializing..."),
    ("实时知识图谱", "Live knowledge graph"),
    ("刷新图谱", "Refresh graph"),
    ("退出全屏", "Exit fullscreen"),
    ("全屏显示", "Fullscreen"),
    ("实时更新中...", "Updating live..."),
    ("图谱数据加载中...", "Loading graph data..."),
    ("等待本体生成", "Waiting for ontology"),
    ("生成完成后将自动开始构建图谱", "Graph build starts when ontology is ready"),
    ("图谱构建中", "Building graph"),
    ("数据即将显示...", "Data will appear shortly..."),
    ("构建流程", "Build pipeline"),
    ("上传文档后，LLM分析文档内容，自动生成适合舆论模拟的本体结构（实体类型 + 关系类型）", "After upload, the LLM builds an ontology for opinion simulation (entity + relation types)"),
    ("生成进度", "Progress"),
    ("生成的实体类型", "Generated entity types"),
    ("生成的关系类型", "Generated relation types"),
    (" 更多关系...", " more relations..."),
    ("等待本体生成...", "Waiting for ontology..."),
    ("等待本体生成完成...", "Waiting for ontology to finish..."),
    ("基于生成的本体，将文档分块后调用 Zep API 构建知识图谱，提取实体和关系", "Chunks docs via Zep API to build the graph and extract entities and relations"),
    ("构建进度", "Build progress"),
    ("构建结果", "Results"),
    ("实体节点", "Entity nodes"),
    ("关系边", "Relation edges"),
    ("实体类型", "Entity types"),
    ("准备进入下一步骤", "Ready for the next step"),
    ("进入环境搭建", "Continue to environment setup"),
    ("项目信息", "Project"),
    ("项目名称", "Name"),
    ("项目ID", "Project ID"),
    ("图谱ID", "Graph ID"),
    ("模拟需求", "Simulation requirement"),
    ("环境搭建功能开发中...", "Environment setup is under development..."),
    ("没有待上传的文件，请返回首页重新操作", "No pending files — return home and try again"),
    ("正在上传文件并分析文档...", "Uploading files and analyzing..."),
    ("本体生成失败", "Ontology generation failed"),
    ("项目初始化失败: ", "Project init failed: "),
    ("加载项目失败", "Failed to load project"),
    ("加载项目失败: ", "Failed to load project: "),
    ("处理失败", "Processing failed"),
    ("正在启动图谱构建...", "Starting graph build..."),
    ("图谱构建任务已启动...", "Graph build task started..."),
    ("启动图谱构建失败", "Failed to start graph build"),
    ("启动图谱构建失败: ", "Failed to start graph build: "),
    ("构建完成，正在加载图谱...", "Build done — loading graph..."),
    ("图谱构建失败: ", "Graph build failed: "),
    ("等待图谱数据...", "Waiting for graph data..."),
    ("未命名", "Unnamed"),
    ("最大化/还原", "Maximize / restore"),
    ("推演记录", "Simulation history"),
    ("分析报告", "Analysis report"),
    (" 个文件", " more files"),
    ("暂无文件", "No files"),
    ("关联文件", "Linked files"),
    ("暂无关联文件", "No linked files"),
    ("推演回放", "Replay"),
    ("Step3「开始模拟」与 Step5「深度互动」需在运行中启动，不支持历史回放", "Step 3 and Step 5 must be started live — not in replay"),
    ("加载中...", "Loading..."),
    ("未命名模拟", "Untitled simulation"),
    ("未知文件", "Unknown file"),
    ("图谱构建", "Graph build"),
    ("环境搭建", "Environment setup"),
    ("开始模拟", "Run simulation"),
    ("报告生成", "Report generation"),
    ("深度互动", "Deep interaction"),
    ("{ graph: '图谱', split: '双栏', workbench: '工作台' }", "{ graph: 'Graph', split: 'Split', workbench: 'Workbench' }"),
    ("进入 Step 3: 开始模拟", "Enter Step 3: Run simulation"),
    ("自定义模拟轮数: ", "Custom max rounds: "),
    ("使用自动配置的模拟轮数", "Using auto max rounds"),
    ("检测到模拟环境正在运行，正在关闭...", "Simulation environment running — shutting down..."),
    ("✓ 模拟环境已关闭", "✓ Simulation environment closed"),
    ("关闭模拟环境失败: ", "Failed to close simulation environment: "),
    ("关闭模拟环境异常: ", "Error closing simulation environment: "),
    ("检测到模拟状态为运行中，正在停止...", "Simulation marked running — stopping..."),
    ("检查模拟状态失败:", "Failed to check simulation status:"),
    ("✓ 模拟已强制停止", "✓ Simulation force-stopped"),
    ("强制停止模拟失败: ", "Force stop failed: "),
    ("强制停止模拟异常: ", "Force stop error: "),
    ("加载模拟数据: ", "Loading simulation: "),
    ("加载模拟数据失败: ", "Failed to load simulation: "),
    ("加载异常: ", "Load error: "),
    ("图谱数据加载成功", "Graph data loaded"),
    ("图谱加载失败: ", "Failed to load graph: "),
    ("SimulationView 初始化", "SimulationView init"),
    ("准备返回 Step 2，正在关闭模拟...", "Returning to Step 2 — closing simulation..."),
    ("正在关闭模拟环境...", "Closing simulation environment..."),
    ("关闭模拟环境失败，尝试强制停止...", "Graceful close failed — force stopping..."),
    ("正在停止模拟进程...", "Stopping simulation process..."),
    ("✓ 模拟已停止", "✓ Simulation stopped"),
    ("停止模拟失败: ", "Stop failed: "),
    ("检查模拟状态失败: ", "Failed to check simulation status: "),
    ("进入 Step 4: 报告生成", "Enter Step 4: Report generation"),
    ("时间配置: 每轮 ", "Timing: "),
    (" 分钟", " min per round"),
    ("获取时间配置失败，使用默认值: ", "Failed to load timing — default: "),
    ("分钟/轮", "min/round"),
    ("开启图谱实时刷新 (30s)", "Graph auto-refresh (30s)"),
    ("停止图谱实时刷新", "Stopped graph auto-refresh"),
    ("SimulationRunView 初始化", "SimulationRunView init"),
    ("加载报告数据: ", "Loading report: "),
    ("获取报告信息失败: ", "Failed to load report: "),
    ("ReportView 初始化", "ReportView init"),
    ("InteractionView 初始化", "InteractionView init"),
    ("默认切换到工作台视角", "Default: workbench view"),
    ("已完成", "Done"),
    ("进行中", "In progress"),
    ("等待中", "Waiting"),
    ("构建失败", "Failed"),
    ("构建完成", "Complete"),
    ("LLM分析文档内容与模拟需求，提取出现实种子，自动生成合适的本体结构", "The LLM reads your docs and prompt, extracts seeds, and builds an ontology"),
    ("正在分析文档...", "Analyzing documents..."),
    ("创建中...", "Creating..."),
    ("图谱构建已完成，请进入下一步进行模拟环境搭建", "Graph done — continue to environment setup"),
    ("未知职业", "Unknown role"),
    ("暂无简介", "No bio"),
    ("男", "Male"),
    ("女", "Female"),
    ("其他", "Other"),
    ("岁", " yrs"),
    ("高峰时段", "Peak"),
    ("工作时段", "Work hours"),
    ("早间时段", "Morning"),
    ("低谷时段", "Off-peak"),
    ("活跃时段", "Active hours"),
    ("发帖/时", "Posts/hr"),
    ("评论/时", "Comments/hr"),
    ("响应延迟", "Latency"),
    ("活跃度", "Activity"),
    ("情感倾向", "Sentiment"),
    ("影响力", "Influence"),
    ("时效权重", "Recency"),
    ("热度权重", "Hotness"),
    ("相关性权重", "Relevance"),
    ("病毒阈值", "Virality threshold"),
    ("回音室强度", "Echo chamber"),
    ("模拟时长", "Duration"),
    ("每轮时长", "Min/round"),
    ("总轮次", "Total rounds"),
    ("每小时活跃", "Active hours factor"),
    ("生成Agent人设", "Generating agent personas"),
    ("生成模拟配置", "Generating simulation config"),
    ("准备模拟脚本", "Preparing scripts"),
    ("开始生成双平台模拟配置...", "Generating dual-platform config..."),
    ("错误：缺少 simulationId", "Error: missing simulationId"),
    ("模拟实例已创建: ", "Simulation created: "),
    ("正在准备模拟环境...", "Preparing environment..."),
    ("检测到已有完成的准备工作，直接使用", "Preparation already done — loading"),
    ("准备任务已启动", "Prepare task started"),
    ("从Zep图谱读取到 ", "Entities from Zep: "),
    (" 个实体", " entities"),
    ("  └─ 实体类型: ", "  └─ entity types: "),
    ("开始轮询准备进度...", "Polling prepare status..."),
    ("准备失败: ", "Prepare failed: "),
    ("准备异常: ", "Prepare error: "),
    ("✓ 准备工作已完成", "✓ Preparation complete"),
    ("✗ 准备失败: ", "✗ Prepare failed: "),
    ("轮询状态失败:", "Poll status failed:"),
    ("开始生成Agent人设...", "Generating agent personas..."),
    ("→ Agent人设 ", "→ Persona "),
    ("✓ 全部 ", "✓ All "),
    (" 个Agent人设生成完成", " personas generated"),
    ("获取 Profiles 失败:", "Failed to fetch profiles:"),
    ("正在生成Agent人设配置...", "Generating persona config..."),
    ("正在调用LLM生成模拟配置参数...", "LLM generating simulation parameters..."),
    ("✓ 模拟配置生成完成", "✓ Simulation config ready"),
    ("  ├─ Agent数量: ", "  ├─ Agents: "),
    ("  ├─ 模拟时长: ", "  ├─ Hours: "),
    ("  ├─ 初始帖子: ", "  ├─ Initial posts: "),
    ("  ├─ 热点话题: ", "  ├─ Hot topics: "),
    ("  └─ 平台配置: Twitter ", "  └─ Platforms: Twitter "),
    ("时间配置: 每轮", "Timing: "),
    ("分钟, 共", " min/round, "),
    ("模拟轮数", "simulation rounds"),
    ("自定义模拟轮数", "custom max rounds"),
    ("自动配置模拟轮数", "auto max rounds"),
    ("轮询", "polling"),
    ("每轮", "per round"),
    ("总轮数", "total rounds"),
    ("最大轮数", "max rounds"),
    ("本轮", "this round"),
    ("轮次", "round"),
    ("叙事方向: ", "Narrative: "),
    ("获取 Config 失败:", "Failed to fetch config:"),
    ("正在加载已有配置数据...", "Loading saved config..."),
    ("已加载 ", "Loaded "),
    (" 个Agent人设", " personas"),
    ("✓ 模拟配置加载成功", "✓ Config loaded"),
    ("配置生成中，开始轮询等待...", "Config generating — polling..."),
    ("加载配置失败: ", "Failed to load config: "),
    ("Step2 环境搭建初始化", "Step 2 environment setup init"),
    ("开始模拟，自定义轮数: ", "Starting with custom rounds: "),
    ("开始模拟，使用自动配置轮数: ", "Starting with auto rounds: "),
    ("启动中...", "Starting..."),
    ("开始生成结果报告", "Generate results report"),
    ("正在启动双平台并行模拟...", "Starting dual-platform simulation..."),
    ("设置最大模拟轮数: ", "Max rounds: "),
    ("已开启动态图谱更新模式", "Dynamic graph updates enabled"),
    ("✓ 已清理旧的模拟日志，重新开始模拟", "✓ Cleared logs — restarting"),
    ("✓ 模拟引擎启动成功", "✓ Simulation engine started"),
    ("启动失败", "Start failed"),
    ("✗ 启动失败: ", "✗ Start failed: "),
    ("✗ 启动异常: ", "✗ Start error: "),
    ("正在停止模拟...", "Stopping simulation..."),
    ("✓ 模拟已停止", "✓ Simulation stopped"),
    ("停止失败: ", "Stop failed: "),
    ("停止异常: ", "Stop error: "),
    ("✓ 检测到所有平台模拟已结束", "✓ All platforms finished"),
    ("✓ 模拟已完成", "✓ Simulation complete"),
    ("获取运行状态失败:", "Failed to get run status:"),
    ("获取详细状态失败:", "Failed to get run detail:"),
    ("报告生成请求已发送，请稍候...", "Report generation requested..."),
    ("正在启动报告生成...", "Starting report generation..."),
    ("✓ 报告生成任务已启动: ", "✓ Report task started: "),
    ("✗ 启动报告生成失败: ", "✗ Report start failed: "),
    ("✗ 启动报告生成异常: ", "✗ Report start error: "),
    ("Step3 模拟运行初始化", "Step 3 simulation init"),
    ("正在生成", "Generating "),
    ("进入深度互动", "Continue to deep interaction"),
    ("与Report Agent对话", "Chat with Report Agent"),
    ("与世界中任意个体对话", "Chat with anyone in the world"),
    ("选择对话对象", "Choose who to chat with"),
    ("发送问卷调查到世界中", "Send survey to the world"),
    ("报告生成智能体的快速对话版本，可调用 4 种专业工具，拥有MiroFish的完整记忆", "Lightweight Report Agent with 4 tools and full MiroFish memory"),
    ("InsightForge 深度归因", "InsightForge deep attribution"),
    ("对齐现实世界种子数据与模拟环境状态，结合Global/Local Memory机制，提供跨时空的深度归因分析", "Aligns seed data with sim state via global/local memory"),
    ("PanoramaSearch 全景追踪", "PanoramaSearch full trace"),
    ("基于图结构的广度遍历算法，重构事件传播路径，捕获全量信息流动的拓扑结构", "Graph BFS to trace propagation topology"),
    ("QuickSearch 快速检索", "QuickSearch"),
    ("基于 GraphRAG 的即时查询接口，优化索引效率，用于快速提取具体的节点属性与离散事实", "GraphRAG-backed quick lookup for facts"),
    ("InterviewSubAgent 虚拟访谈", "InterviewSubAgent"),
    ("自主式访谈，能够并行与模拟世界中个体进行多轮对话，采集非结构化的观点数据与心理状态", "Parallel interviews for qualitative data"),
    ("简介", "Bio"),
    ("与 Report Agent 对话，深入了解报告内容", "Chat with Report Agent about the report"),
    ("与模拟个体对话，了解他们的观点", "Chat with sim agents"),
    ("输入您的问题...", "Type your question..."),
    ("选择调查对象", "Survey recipients"),
    ("已选 ", "Selected "),
    ("问卷问题", "Survey question"),
    ("输入您想问所有被选中对象的问题...", "Question for all selected agents..."),
    ("发送问卷", "Send survey"),
    ("调查结果", "Results"),
    (" 条回复", " replies"),
    ("发送失败: ", "Send failed: "),
    ("抱歉，发生了错误: ", "Sorry, an error occurred: "),
    ("无响应", "No response"),
    ("向 Report Agent 发送: ", "To Report Agent: "),
    ("Report Agent 已回复", "Report Agent replied"),
    ("请求失败", "Request failed"),
    ("请先选择一个模拟个体", "Select an agent first"),
    ("提问者", "User"),
    ("你", "Agent"),
    ("选择对话对象: ", "Chat target: "),
    ("向 ", "To "),
    (" 发送: ", ": "),
    ("发送问卷给 ", "Survey to "),
    (" 个对象...", " agents..."),
    ("收到 ", "Received "),
    ("问卷发送失败: ", "Survey failed: "),
    ("加载报告失败: ", "Failed to load report: "),
    ("报告数据加载完成", "Report loaded"),
    ("加载报告日志失败: ", "Failed to load report logs: "),
    ("加载了 ", "Loaded "),
    (" 个模拟个体", " agents"),
    ("加载模拟个体失败: ", "Failed to load agents: "),
    ("Step5 深度互动初始化", "Step 5 interaction init"),
    ("收起 ▲", "Collapse ▲"),
    ("展开全部 ", "Expand all "),
    (" 条 ▼", " ▼"),
    (" 个 ▼", " ▼"),
    ("预测场景: ", "Scenario: "),
    ("当前关键记忆", "Key memories"),
    ("核心实体", "Core entities"),
    ("关系链", "Relation chains"),
    ("子问题", "Sub-questions"),
    ("时序记忆中所关联的最新关键事实", "Latest key facts in temporal memory"),
    ("暂无当前关键记忆", "No key memories"),
    ("暂无核心实体", "No core entities"),
    ("暂无关系链", "No relation chains"),
    ("当前有效记忆", "Active facts"),
    ("历史记忆", "Historical facts"),
    ("涉及实体", "Related entities"),
    ("暂无当前有效记忆", "No active facts"),
    ("暂无历史记忆", "No historical facts"),
    ("暂无涉及实体", "No related entities"),
    ("世界1", "World 1"),
    ("世界2", "World 2"),
    ("`共 ${props.result.facts.length} 条`", "`Total ${props.result.facts.length}`"),
    ("`共 ${props.result.entities.length} 个`", "`Total ${props.result.entities.length}`"),
    ("`共 ${props.result.relations.length} 条`", "`Total ${props.result.relations.length}`"),
    ("`共 ${props.result.subQueries.length} 个`", "`Total ${props.result.subQueries.length}`"),
    ("`共 ${props.result.activeFacts.length} 条`", "`Total ${props.result.activeFacts.length}`"),
    ("`共 ${props.result.historicalFacts.length} 条`", "`Total ${props.result.historicalFacts.length}`"),
    ("`共 ${props.result.edges.length} 条`", "`Total ${props.result.edges.length}`"),
    ("`共 ${props.result.nodes.length} 个`", "`Total ${props.result.nodes.length}`"),
    ("选择理由", "Selection rationale"),
    ("搜索: ", "Search: "),
    ("事实", "Facts"),
    ("关系", "Relations"),
    ("（该平台未获得回复）", "(No reply on this platform)"),
    ("MiroFish - 社交媒体舆论模拟系统", "MiroFish — social simulation platform"),
    ("MiroFish - 预测万物", "MiroFish — simulate anything"),
    ("MiroFish - 简洁通用的群体智能引擎，预测万物", "MiroFish — a lean collective intelligence engine to simulate anything"),
    ("使用 Vue Router 来管理页面", "Page routing via Vue Router"),
    ("全局样式重置", "Global reset"),
    ("滚动条样式", "Scrollbars"),
    ("全局按钮样式", "Global buttons"),
]

# Second pass: fix mixed EN/ZH fragments from overlapping replacements (longest first)
POST_PAIRS: list[tuple[str, str]] = [
    ("等待Ontology generation完成...", "Waiting for ontology to complete..."),
    ("等待Ontology generation...", "Waiting for ontology..."),
    ("等待Ontology generation", "Waiting for ontology"),
    ("Ontology generation中", "Ontology in progress"),
    ("Ontology generation失败", "Ontology generation failed"),
    ("Ontology generation进度", "Ontology progress"),
    ("Ontology generation阶段", "Ontology phase"),
    (" }} 节点</span>", " }} nodes</span>"),
    (" }} 关系</span>", " }} relations</span>"),
    ("接口说明", "What it does"),
    ("Graph build中", "Graph building"),
    ("继续polling构建中的任务", "Keep polling in-flight build tasks"),
    ("加载Done的图谱", "Load completed graph"),
    ("Run simulation，自定义轮数:", "Starting simulation, custom rounds:"),
    ("Run simulation，使用自动配置轮数:", "Starting simulation, auto rounds:"),
    ("设置最大simulation rounds:", "Max simulation rounds:"),
    ("格式化轮数显示（当前轮/total rounds）", "Format round display (current/total)"),
    ("/* rounds数进度显示 */", "/* Round progress */"),
    ("底部 rounds数进度显示", "Bottom round progress"),
    ("simulation rounds配置", "Simulation rounds config"),
    ("只有在配置生成完成且轮数计算出来后才显示", "Shown after config is ready and round count is known"),
    ("确保max rounds不小于40（推荐值），避免滑动条范围异常", "Keep max rounds ≥ 40 (recommended) so the slider stays valid"),
    ("// 如果是从 Step 2 进入 Step 3，记录simulation rounds配置", "// From Step 2 to Step 3: log simulation rounds"),
    ("// 记录simulation rounds配置", "// Log simulation rounds"),
    ("<!-- 顶部导航栏 -->", "<!-- Top navigation -->"),
    ("<!-- 中间步骤指示器 -->", "<!-- Step indicator -->"),
    ("<!-- 主内容区 -->", "<!-- Main -->"),
    ("<!-- 左侧: 实时图谱展示 -->", "<!-- Left: live graph -->"),
    ("<!-- 图谱可视化（只要有数据就显示） -->", "<!-- Graph viz (when data exists) -->"),
    ("<!-- 构建中提示 -->", "<!-- Building hint -->"),
    ("<!-- 节点/边详情面板 -->", "<!-- Node/edge detail panel -->"),
    ("<!-- 节点详情 -->", "<!-- Node detail -->"),
    ("<!-- 边详情 -->", "<!-- Edge detail -->"),
    ("<!-- Relations展示 -->", "<!-- Relations -->"),
    ("<!-- 加载状态 -->", "<!-- Loading -->"),
    ("<!-- 等待构建 -->", "<!-- Waiting for build -->"),
    ("<!-- 构建中但还没有数据 -->", "<!-- Building, no data yet -->"),
    ("<!-- 错误状态 -->", "<!-- Error -->"),
    ("<!-- 图谱图例 -->", "<!-- Graph legend -->"),
    ("<!-- 右侧: Build pipeline详情 -->", "<!-- Right: build pipeline -->"),
    ("<!-- 已生成的本体信息 -->", "<!-- Generated ontology -->"),
    ("<!-- 等待状态 -->", "<!-- Waiting -->"),
    ("<!-- 等待本体完成 -->", "<!-- Waiting for ontology -->"),
    ("<!-- 阶段3: 完成 -->", "<!-- Stage 3: done -->"),
    ("<!-- 下一步按钮 -->", "<!-- Next button -->"),
    ("<!-- Project面板 -->", "<!-- Project panel -->"),
    ("// 当前Project ID（可能从'new'变为实际ID）", "// Current project id (may change from 'new')"),
    ("// -1: 上传中, 0: Ontology in progress, 1: Graph build, 2: 完成", "// -1: uploading, 0: ontology, 1: graph, 2: done"),
    ("// 选中的节点或边", "// Selected node or edge"),
    ("// DOM引用", "// DOM refs"),
    ("// polling定时器", "// Poll timers"),
    ("// 计算属性", "// Computed"),
    ("  return '初始化中'", "  return 'Initializing'"),
    ("// 方法", "// Methods"),
    ("// 关闭详情面板", "// Close detail panel"),
    ("// 格式化日期", "// Format date"),
    ("// 选中节点", "// Select node"),
    ("// 选中边", "// Select edge"),
    ("// 初始化 - 处理新建项目或加载已有项目", "// Init: new or existing project"),
    ("// 新建项目：从 store 获取待上传的数据", "// New project: pending upload from store"),
    ("// 加载已有项目", "// Load existing project"),
    ("// 处理新建项目 - 调用 ontology/generate API", "// New project: ontology/generate"),
    ("// 构建 FormData", "// Build FormData"),
    ("// 调用Ontology generation API", "// Call ontology/generate"),
    ("// 清除待上传数据", "// Clear pending upload"),
    ("// 更新Project ID和数据", "// Update project id and data"),
    ("// 更新URL（不刷新页面）", "// Update URL (no reload)"),
    ("// 自动开始Graph build", "// Auto-start graph build"),
    ("'未知错误'", "'Unknown error'"),
    ("// 加载已有项目数据", "// Load existing project data"),
    ("// 开始构建图谱", "// Start graph build"),
    ("// 设置初始进度", "// Initial progress"),
    ("// 保存 task_id 用于polling", "// Keep task_id for polling"),
    ("// 启动图谱数据polling（独立于任务状态polling）", "// Poll graph data (separate from task poll)"),
    ("// 启动任务状态polling", "// Poll task status"),
    ("// 图谱数据polling定时器", "// Graph data poll timer"),
    ("// 启动图谱数据polling", "// Start graph data polling"),
    ("// 立即获取一次", "// Fetch once immediately"),
    ("// 每 10 秒自动获取一次图谱数据", "// Refresh graph every 10s"),
    ("// 手动Refresh graph", "// Manual graph refresh"),
    ("// 停止图谱数据polling", "// Stop graph data polling"),
    ("// 获取图谱数据", "// Fetch graph data"),
    ("// 先获取Project以获取 graph_id", "// Load project for graph_id"),
    ("// 获取图谱数据", "// Fetch graph payload"),
    ("// 数据有变化时更新渲染", "// Re-render when data changes"),
    ("// polling任务状态", "// Poll task status"),
    ("// 立即执行一次查询", "// Query once"),
    ("// 然后定时polling", "// Then poll on interval"),
    ("// 查询任务状态", "// Query task status"),
    ("// 更新进度显示", "// Update progress UI"),
    ("// 重新加载Project数据获取 graph_id", "// Reload project for graph_id"),
    ("// 最终加载完整图谱数据", "// Load full graph"),
    ("// 清除进度显示", "// Clear progress UI"),
    ("// 加载图谱数据", "// Load graph data"),
    ("// 渲染图谱 (D3.js)", "// Render graph (D3)"),
    ("// 获取容器尺寸", "// Container size"),
    ("// 处理节点数据", "// Node data"),
    ("// 显示空状态", "// Empty state"),
    ("// 创建节点映射用于查找名称", "// Node map for labels"),
    ("// 保存原始数据", "// Keep raw row"),
    ("// 创建节点ID集合用于过滤有效边", "// Node id set for edges"),
    ("// 颜色映射", "// Colors"),
    ("// 力导向布局", "// Force layout"),
    ("// 添加缩放功能", "// Zoom/pan"),
    ("// 绘制边（包含可点击的透明宽线）", "// Edges + hit areas"),
    ("// 可见的细线", "// Visible edge stroke"),
    ("// 透明的宽线用于点击", "// Wide hit target"),
    ("// 边标签", "// Edge labels"),
    ("// 绘制节点", "// Draw nodes"),
    ("// 点击空白处关闭详情面板", "// Click away closes panel"),
    ("// 更新所有边的位置（包括可见线和透明点击区域）", "// Sync edge paths"),
    ("// 更新边标签位置", "// Sync label positions"),
    ("// 监听图谱数据变化", "// Watch graph data"),
    ("// 生命周期", "// Lifecycle"),
    ("/* 变量 */", "/* Vars */"),
    ("/* 导航栏 */", "/* Nav */"),
    ("/* 主内容区 */", "/* Main */"),
    ("/* 左侧面板 - 50% default */", "/* Left panel */"),
    ("/* 图谱容器 */", "/* Graph container */"),
    ("/* 节点/边详情面板 */", "/* Detail panel */"),
    ("/* 边详情关系展示 */", "/* Edge relations */"),
    ("/* 图谱图例 */", "/* Legend */"),
    ("/* 右侧面板 - 50% default */", "/* Right panel */"),
    ("/* 流程内容 */", "/* Pipeline content */"),
    ("/* 流程阶段 */", "/* Stages */"),
    ("/* 阶段详情 */", "/* Stage detail */"),
    ("/* 实体标签 */", "/* Entity tags */"),
    ("/* 关系列表 */", "/* Relations list */"),
    ("/* Ontology generation进度 */", "/* Ontology progress */"),
    ("/* 等待状态 */", "/* Waiting */"),
    ("/* 进度条 */", "/* Progress bar */"),
    ("/* 构建结果 */", "/* Build results */"),
    ("/* 下一步按钮 */", "/* Next button */"),
    ("/* Project信息面板 */", "/* Project panel */"),
    ("/* 响应式 */", "/* Responsive */"),
]

ROOT = Path(__file__).resolve().parents[1]


def should_process(path: Path) -> bool:
    if path.suffix not in {".vue", ".js", ".ts", ".tsx", ".py", ".md", ".json", ".yml", ".yaml", ".html"}:
        return False
    parts = path.parts
    if "node_modules" in parts or ".git" in parts:
        return False
    return True


def translate_text(s: str) -> str:
    for zh, en in PAIRS:
        s = s.replace(zh, en)
    for zh, en in POST_PAIRS:
        s = s.replace(zh, en)
    # Fix accidental breakage: " 轮" -> " rounds" split 轮询 into rounds+询
    s = s.replace("rounds" + "\u8be2", "polling")  # \u8be2 = 询
    return s


def main() -> None:
    targets = [ROOT / "frontend", ROOT / "backend", ROOT / "package.json", ROOT / "README.md"]
    changed = 0
    for base in targets:
        if not base.exists():
            continue
        if base.is_file():
            paths = [base]
        else:
            paths = list(base.rglob("*"))
        for path in paths:
            if not path.is_file() or not should_process(path):
                continue
            try:
                text = path.read_text(encoding="utf-8")
            except (OSError, UnicodeDecodeError):
                continue
            new = translate_text(text)
            if new != text:
                path.write_text(new, encoding="utf-8")
                changed += 1
                print(path.relative_to(ROOT))
    print(f"Files modified: {changed}", file=sys.stderr)


if __name__ == "__main__":
    main()
